### ISSUE TITLE
Timestamp block header — backwards compatibility issues

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#248]
@i1t There are backwards compatibility bugs with nil timestamps for existing blocks. Can you look into this?

Here are some logs after I [implemented](https://github.com/turinginc/credo-core-node/compare/rlp-tmp-fix) a temporary fix for https://github.com/turinginc/credo-core-node/issues/243:

```17:17:45.969 [error] GenServer #PID<0.2265.0> terminating
** (UndefinedFunctionError) function nil.timestamp/0 is undefined
    nil.timestamp()
    (credo_core_node) lib/credo_core_node/blockchain/block_producer.ex:21: CredoCoreNode.Blockchain.BlockProducer.retries_since/2
    (credo_core_node) lib/credo_core_node/blockchain/block_changeset.ex:89: CredoCoreNode.Blockchain.BlockChangeset.validate_miner/1
    (credo_core_node) lib/mnesia/repo.ex:140: Mnesia.Repo.write/2
    (credo_core_node) lib/credo_core_node/workers/block_syncer.ex:159: CredoCoreNode.Workers.BlockSyncer.process_headers_group/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (credo_core_node) lib/credo_core_node/workers/block_syncer.ex:39: CredoCoreNode.Workers.BlockSyncer.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
Last message: :sync_blocks
17:17:45.969 [info] Initializing the block syncer...
17:17:45.972 [info] Syncing block headers from 13.57.51.137:9332
17:17:46.496 [info] No response or incorrect response
17:17:46.505 [info] Connection attempt #6. Trying to connect to 166.137.177.245:9332
17:17:51.015 [error] GenServer #PID<0.2267.0> terminating
** (UndefinedFunctionError) function nil.timestamp/0 is undefined
    nil.timestamp()
    (credo_core_node) lib/credo_core_node/blockchain/block_producer.ex:21: CredoCoreNode.Blockchain.BlockProducer.retries_since/2
    (credo_core_node) lib/credo_core_node/blockchain/block_changeset.ex:89: CredoCoreNode.Blockchain.BlockChangeset.validate_miner/1
    (credo_core_node) lib/mnesia/repo.ex:140: Mnesia.Repo.write/2
    (credo_core_node) lib/credo_core_node/workers/block_syncer.ex:159: CredoCoreNode.Workers.BlockSyncer.process_headers_group/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (credo_core_node) lib/credo_core_node/workers/block_syncer.ex:39: CredoCoreNode.Workers.BlockSyncer.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
Last message: :sync_blocks```

**Comment by malroc** [comment]
@macgregordennis @i1t actually I don't really think we need to think about any kind of backwards-compatibility: after I changed private key -> address mapping logic, all existing blocks are invalid (as they use old addresses).

**Comment by i1t** [comment]
Agreed with @malroc. Still, addressed the issue in https://github.com/turinginc/credo-core-node/pull/246/commits/27a6b9ff22b3377613e459078d85d2828fb32405 and reinterpreted https://github.com/turinginc/credo-core-node/compare/rlp-tmp-fix as https://github.com/turinginc/credo-core-node/pull/246/commits/011f8adfd93189bb9384f08d2ae52810d1dcf7a5 (https://github.com/turinginc/credo-core-node/pull/246).

**Comment by i1t** [comment]
@malroc, speaking of private key -> address mapping logic change — `master` is now seriously red with 22 failing tests, and that complicates the testing of new commits. Are you currently working on fixing tests or is it a pending task?

**Comment by malroc** [comment]
@i1t yes, working on it

**Comment by macgregordennis** [comment]
> actually I don't really think we need to think about any kind of backwards-compatibility: after I changed private key -> address mapping logic, all existing blocks are invalid (as they use old addresses).

@malroc @i1t Sounds great. We can remove this backwards compatibility code either prior to shipping the main net or when we make a new test network.

> yes, working on it

Good to hear

**Comment by macgregordennis** [comment]
Waiting to close this until https://github.com/turinginc/credo-core-node/pull/246 is merged.
