### ISSUE TITLE
RLP decoding bug

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#252]
Logs:

```20:02:59.756 [info] Received block headers request: 8DE4C90522A0F848A63AB0337798CE17821007458B50B82152F1C8D4E98DEA21D443CCA397A4952139673081AC38F74F9E9E4B6F805B9C9BB9E8E5F15A7050156544F57850BB74689A4B5EA3236D54BCE439FBFDEACA24F9C811276C0B38C51F7DF8CDF3B557AAB7C350DD09BB087EF0714F7607E53E2AECD4605DBE63FC48F4
20:02:59.760 [error] GenServer CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient0 terminating
** (Protocol.UndefinedError) protocol ExRLP.Encode not implemented for nil. This protocol is implemented for: CredoCoreNode.Mining.Vote, CredoCoreNode.Blockchain.Transaction, CredoCoreNode.Pool.PendingBlock, CredoCoreNode.State.AccountState, CredoCoreNode.Blockchain.Block, CredoCoreNode.Pool.PendingTransaction, Integer, List, BitString
    (ex_rlp) deps/ex_rlp/lib/ex_rlp/encode.ex:1: ExRLP.Encode.impl_for!/1
    (ex_rlp) deps/ex_rlp/lib/ex_rlp/encode.ex:2: ExRLP.Encode.encode/2
    (ex_rlp) lib/ex_rlp/encode.ex:71: ExRLP.Encode.List.encode_items/2
    (ex_rlp) lib/ex_rlp/encode.ex:61: ExRLP.Encode.List.encode/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (credo_core_node) lib/credo_core_node_web/channels/node_socket/v1/event_channel_client.ex:24: CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient0.handle_in/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Last message: {:trigger, "blocks:headers_request", %{"limit" => 50, "offset" => 1, "remote_session_id" => "CB0hgyf9LVIz/Fng6QtyqHQwMd8w2J0St8URfa+lhrI=", "request_id" => "8DE4C90522A0F848A63AB0337798CE17821007458B50B82152F1C8D4E98DEA21D443CCA397A4952139673081AC38F74F9E9E4B6F805B9C9BB9E8E5F15A7050156544F57850BB74689A4B5EA3236D54BCE439FBFDEACA24F9C811276C0B38C51F7DF8CDF3B557AAB7C350DD09BB087EF0714F7607E53E2AECD4605DBE63FC48F4"}, nil}
20:02:59.760 [info] Initializing the connection manager...
20:02:59.761 [warn] Socket terminated: {%Protocol.UndefinedError{description: "", protocol: ExRLP.Encode, value: nil}, [{ExRLP.Encode, :impl_for!, 1, [file: 'deps/ex_rlp/lib/ex_rlp/encode.ex', line: 1]}, {ExRLP.Encode, :encode, 2, [file: 'deps/ex_rlp/lib/ex_rlp/encode.ex', line: 2]}, {ExRLP.Encode.List, :encode_items, 2, [file: 'lib/ex_rlp/encode.ex', line: 71]}, {ExRLP.Encode.List, :encode, 2, [file: 'lib/ex_rlp/encode.ex', line: 61]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1327]}, {CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient0, :handle_in, 3, [file: 'lib/credo_core_node_web/channels/node_socket/v1/event_channel_client.ex', line: 24]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}]}
20:02:59.762 [error] GenServer CredoCoreNodeWeb.NodeSocket.V1.SocketClient0 terminating
** (Protocol.UndefinedError) protocol ExRLP.Encode not implemented for nil. This protocol is implemented for: CredoCoreNode.Mining.Vote, CredoCoreNode.Blockchain.Transaction, CredoCoreNode.Pool.PendingBlock, CredoCoreNode.State.AccountState, CredoCoreNode.Blockchain.Block, CredoCoreNode.Pool.PendingTransaction, Integer, List, BitString
    (ex_rlp) deps/ex_rlp/lib/ex_rlp/encode.ex:1: ExRLP.Encode.impl_for!/1
    (ex_rlp) deps/ex_rlp/lib/ex_rlp/encode.ex:2: ExRLP.Encode.encode/2
    (ex_rlp) lib/ex_rlp/encode.ex:71: ExRLP.Encode.List.encode_items/2
    (ex_rlp) lib/ex_rlp/encode.ex:61: ExRLP.Encode.List.encode/2
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (credo_core_node) lib/credo_core_node_web/channels/node_socket/v1/event_channel_client.ex:24: CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient0.handle_in/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Last message: {:EXIT, #PID<0.2251.0>, {%Protocol.UndefinedError{description: "", protocol: ExRLP.Encode, value: nil}, [{ExRLP.Encode, :impl_for!, 1, [file: 'deps/ex_rlp/lib/ex_rlp/encode.ex', line: 1]}, {ExRLP.Encode, :encode, 2, [file: 'deps/ex_rlp/lib/ex_rlp/encode.ex', line: 2]}, {ExRLP.Encode.List, :encode_items, 2, [file: 'lib/ex_rlp/encode.ex', line: 71]}, {ExRLP.Encode.List, :encode, 2, [file: 'lib/ex_rlp/encode.ex', line: 61]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1327]}, {CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient0, :handle_in, 3, [file: 'lib/credo_core_node_web/channels/node_socket/v1/event_channel_client.ex', line: 24]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}]}}```

Potentially related to backwards compatibility issues partially resolved in #251.

**Comment by macgregordennis** [comment]
Fixed
