### ISSUE TITLE
LevelDB reliability issue.

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#273]
@malroc @AlimovSV I just observed this behavior when mining locally:

<img width="1956" alt="Screen Shot 2019-09-17 at 11 34 05 AM" src="https://user-images.githubusercontent.com/1322709/65069233-1f220100-d93f-11e9-8ba1-39dd2f9e5873.png">

<img width="1956" alt="Screen Shot 2019-09-17 at 11 34 11 AM" src="https://user-images.githubusercontent.com/1322709/65069237-21845b00-d93f-11e9-9f4c-77975103d7c3.png">

<img width="1956" alt="Screen Shot 2019-09-17 at 11 34 15 AM" src="https://user-images.githubusercontent.com/1322709/65069247-25b07880-d93f-11e9-850f-d1941f3d47fc.png">

It looks like there was a LevelDB error interfering with mining, and the error persisted across restarts of the mining operator worker. We need improved supervision or error handling here to address this scenario.

**Comment by AlimovSV** [comment]
Yes, I seen this error when mining locally with the fake genesis block. Looks like we somewhere do not close a connection to the leveldb and miner can't access the trie 5 times and fail.

**Comment by malroc** [comment]
@AlimovSV @macgregordennis accessing LevelDB is somewhat tricky as you always need to close a previously opened connection before opening it in another place. It looks like the issue was introduced recently

**Comment by macgregordennis** [comment]
Right, I've seen it more lately. Two ideas:
1. Find and use a global mechanism for shutting LevelDB connections that can be called in this scenario.
2. Implement an improved mechanism for handling a LevelDB connection reference, such as through storing it in a persistent cache that can be accessed from a new process if another process failed. This could also improve upon the current approach of retrying to access LevelDB by instead directly checking whether it's in-use and waiting or accessing it accordingly.

Thoughts?

**Comment by macgregordennis** [comment]
I think the latter is the better option that could replace this: https://github.com/turinginc/credo-core-node/blob/master/lib/mpt/repo_manager.ex#L53-L65

**Comment by malroc** [comment]
@macgregordennis though I generally like the idea, I'm actually against making any major architecture improvements right now as it may introduce unexpected side-effects/issues/etc
Let's just fix the current issue and delay architecture changes until after the mainnet launch

**Comment by i1t** [comment]
On current `master` LevelDB might cause deletion of confirmed blocks (including genesis block — see below):

```
[info] Received block: %CredoCoreNode.Blockchain.Block{body: nil, hash: "15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56", is_valid: nil, number: 3, prev_hash: "96F292295F8BB7A675DC666C96D1E72255405D25D0CF8CCA4B69EED77F0DEC09", receipt_root: "", state_root: "A3DA70CDCDCF5C29F7D0E46177A7D4D4BDF9300477FD5B7D18FDAF76117004E8", timestamp: 1568161265, tx_root: "5CE8E3B6063EE95453FBBAD9E8D09D5755EB971DACBD34659BA16CBAF12A4507"}
[info] Writing block and fetching body...
[info] Writing block and fetching body...
[info] Writing block and fetching body...
[info] Writing block and fetching body...
[warn] MPT init error (attempt #1): can't access LevelDB at '/Users/i1t/credo/dev/testnet_d/leveldb/state/state'
[warn] MPT init error (attempt #2): can't access LevelDB at '/Users/i1t/credo/dev/testnet_d/leveldb/state/state'
[warn] MPT init error (attempt #3): can't access LevelDB at '/Users/i1t/credo/dev/testnet_d/leveldb/state/state'
[info] Writing and propagating block 15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56
[info] Propagating: %CredoCoreNode.Blockchain.Block{body: <<249, 2, 17, 249, 1, 74, 3, 168, 66, 69, 68, 67, 53, 70, 68, 53, 48, 49, 53, 70, 56, 66, 68, 68, 68, 52, 53, 54, 48, 68, 50, 49, 57, 67, 65, 53, 49, 66, 49, 69, 52, 66, 55, 52, 67, 49, 52, 55, 135, ...>>, hash: "15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56", is_valid: true, number: 3, prev_hash: "96F292295F8BB7A675DC666C96D1E72255405D25D0CF8CCA4B69EED77F0DEC09", receipt_root: "", state_root: "A3DA70CDCDCF5C29F7D0E46177A7D4D4BDF9300477FD5B7D18FDAF76117004E8", timestamp: 1568161265, tx_root: "5CE8E3B6063EE95453FBBAD9E8D09D5755EB971DACBD34659BA16CBAF12A4507"}
[info] sending to 54.215.220.142
[warn] MPT init error (attempt #4): can't access LevelDB at '/Users/i1t/credo/dev/testnet_d/leveldb/state/state'
[info] Writing and propagating block 15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56
[info] Propagating: %CredoCoreNode.Blockchain.Block{body: <<249, 2, 17, 249, 1, 74, 3, 168, 66, 69, 68, 67, 53, 70, 68, 53, 48, 49, 53, 70, 56, 66, 68, 68, 68, 52, 53, 54, 48, 68, 50, 49, 57, 67, 65, 53, 49, 66, 49, 69, 52, 66, 55, 52, 67, 49, 52, 55, 135, ...>>, hash: "15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56", is_valid: true, number: 3, prev_hash: "96F292295F8BB7A675DC666C96D1E72255405D25D0CF8CCA4B69EED77F0DEC09", receipt_root: "", state_root: "A3DA70CDCDCF5C29F7D0E46177A7D4D4BDF9300477FD5B7D18FDAF76117004E8", timestamp: 1568161265, tx_root: "5CE8E3B6063EE95453FBBAD9E8D09D5755EB971DACBD34659BA16CBAF12A4507"}
[info] sending to 54.215.220.142
[warn] MPT init error (attempt #5): can't access LevelDB at '/Users/i1t/credo/dev/testnet_d/leveldb/state/state'
[info] Writing and propagating block 15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56
[info] Propagating: %CredoCoreNode.Blockchain.Block{body: <<249, 2, 17, 249, 1, 74, 3, 168, 66, 69, 68, 67, 53, 70, 68, 53, 48, 49, 53, 70, 56, 66, 68, 68, 68, 52, 53, 54, 48, 68, 50, 49, 57, 67, 65, 53, 49, 66, 49, 69, 52, 66, 55, 52, 67, 49, 52, 55, 135, ...>>, hash: "15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56", is_valid: true, number: 3, prev_hash: "96F292295F8BB7A675DC666C96D1E72255405D25D0CF8CCA4B69EED77F0DEC09", receipt_root: "", state_root: "A3DA70CDCDCF5C29F7D0E46177A7D4D4BDF9300477FD5B7D18FDAF76117004E8", timestamp: 1568161265, tx_root: "5CE8E3B6063EE95453FBBAD9E8D09D5755EB971DACBD34659BA16CBAF12A4507"}
[info] sending to 54.215.220.142
[info] Deleting invalid block 15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56
[info] sending to 13.57.222.76
[info] sending to 13.57.222.76
[info] sending to 13.57.222.76
[error] GenServer CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient1 terminating
** (stop) exited in: GenServer.call(CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient1, {:push, "blocks:create", %{rlp: "f8cdb8403936463239323239354638424237413637354443363636433936443145373232353534303544323544304346384343413442363945454437374630444543303903845d783df1b8404133444137304344434443463543323946374430453436313737413744344434424446393330303437374644354237443138464441463736313137303034453880b84035434538453342363036334545393534353346424241443945384430394435373535454239373144414342443334363539424131364342414631324134353037", session_ids: ["ab3FZtTeykaWWQhtIY61cxTIzIlWnXVZ5CUEnSX/kf8="]}, 5000}, 5000)
    ** (EXIT) process attempted to call itself
    (elixir) lib/gen_server.ex:982: GenServer.call/3
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (credo_core_node) lib/credo_core_node/blockchain/blockchain.ex:588: CredoCoreNode.Blockchain.propagate_block/2
    (credo_core_node) lib/credo_core_node/blockchain/blockchain.ex:565: CredoCoreNode.Blockchain.fetch_block_body/3
    (credo_core_node) lib/credo_core_node_web/channels/node_socket/v1/event_channel_client.ex:7: CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient1.handle_record/2
    (credo_core_node) lib/credo_core_node_web/channels/node_socket/v1/event_channel_client.ex:7: CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient1.handle_in/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:trigger, "blocks:create", %{"rlp" => "f8cdb8403936463239323239354638424237413637354443363636433936443145373232353534303544323544304346384343413442363945454437374630444543303903845d783df1b8404133444137304344434443463543323946374430453436313737413744344434424446393330303437374644354237443138464441463736313137303034453880b84035434538453342363036334545393534353346424241443945384430394435373535454239373144414342443334363539424131364342414631324134353037", "session_ids" => ["35pOa2v4kVNCmcRnTxqr8s5eb0O6srf8GxffwpxGxGU="]}, nil}
State: %{join_push: %{event: "phx_join", payload: %{}, ref: "2", topic: "events:all"}, join_timer: #Reference<0.96014279.878968833.88824>, leave_push: nil, opts: [socket: CredoCoreNodeWeb.NodeSocket.V1.SocketClient0, topic: "events:all", caller: #PID<0.2088.0>], pushes: [], sender: CredoCoreNodeWeb.NodeSocket.V1.EventChannelClient1, socket: CredoCoreNodeWeb.NodeSocket.V1.SocketClient0, state: :joined, topic: "events:all"}
```

As I see it, shortly after 

`[warn] MPT init error (attempt #5): can't access LevelDB at '/Users/i1t/credo/dev/testnet_d/leveldb/state/state'`

we get

`[info] Deleting invalid block 15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56`.

The result: `list_blocks()` return blocks with numbers 7-4 (blocks 3-0 got lost):

```
[
  %CredoCoreNode.Blockchain.Block{
    body: nil,
    hash: "273F5A3BD3BA0C26C3B48AF135EE7E56BD5D016C6EC3ADF454893838207EA3A7",
    is_valid: true,
    number: 7,
    prev_hash: "9C984D6BFF277A0FA3A6BA66C227CD2DC245CE3D12CA0068D5CA84F603A324AF",
    receipt_root: "",
    state_root: "6D8F8D012634F8FA2D198AC9ADF31BE5FE911DD6D736B656FC55DFA761AC361B",
    timestamp: 1568745662,
    tx_root: "405E13FC2E53651B54BF01A83D2812E20BD2157A6605926140F6353D42C806AC"
  },
  %CredoCoreNode.Blockchain.Block{
    body: nil,
    hash: "9C984D6BFF277A0FA3A6BA66C227CD2DC245CE3D12CA0068D5CA84F603A324AF",
    is_valid: true,
    number: 6,
    prev_hash: "BF267941976DB88658C7F1CF222B363AC6B9ABC5CFD49C70A6BDC661F02AE378",
    receipt_root: "",
    state_root: "D24FC8D7D00F8DA5AC74B97DAD2EF9A170BE87CFB887FAEFDD69B8D598C0A4A3",
    timestamp: 1568745092,
    tx_root: "1E32475F9F276C4DB0BDE223B551043ED54184E47E00C919EB8A793C846C2929"
  },
  %CredoCoreNode.Blockchain.Block{
    body: nil,
    hash: "BF267941976DB88658C7F1CF222B363AC6B9ABC5CFD49C70A6BDC661F02AE378",
    is_valid: true,
    number: 5,
    prev_hash: "54DBA955204308DE7966601B8D0DD85F38F892B318C06CE9311E90E92EDA37C4",
    receipt_root: "",
    state_root: "3FFF1FC00EE9CD196E2AC19FA35D68518610A301B767F5BCC3E13C6A878DE600",
    timestamp: 1568161552,
    tx_root: "0D061FE2B5EF33511E2FC40F4F50D960EE3366A4D22302E690BAB791C06AAC26"
  },
  %CredoCoreNode.Blockchain.Block{
    body: nil,
    hash: "54DBA955204308DE7966601B8D0DD85F38F892B318C06CE9311E90E92EDA37C4",
    is_valid: true,
    number: 4,
    prev_hash: "15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56",
    receipt_root: "",
    state_root: "74C091866A0391F3E3D3AFEF392E5FF2E35CA75C6E275C5E7BAB94B840741E2A",
    timestamp: 1568161409,
    tx_root: "432FF2A2F20779BE06A2F6B4189E5EDBE8A2DD403680B415C896CAA9DB5D8A47"
  },
  %CredoCoreNode.Blockchain.Block{
    body: nil,
    hash: "15EA11A0042AB96971123F7F937A6D6AC5A57C830CF6A0FBE99F9FA52F4BFA56",
    is_valid: true,
    number: 3,
    prev_hash: "96F292295F8BB7A675DC666C96D1E72255405D25D0CF8CCA4B69EED77F0DEC09",
    receipt_root: "",
    state_root: "A3DA70CDCDCF5C29F7D0E46177A7D4D4BDF9300477FD5B7D18FDAF76117004E8",
    timestamp: 1568161265,
    tx_root: "5CE8E3B6063EE95453FBBAD9E8D09D5755EB971DACBD34659BA16CBAF12A4507"
  },
  %CredoCoreNode.Blockchain.Block{
    body: nil,
    hash: "96F292295F8BB7A675DC666C96D1E72255405D25D0CF8CCA4B69EED77F0DEC09",
    is_valid: true,
    number: 2,
    prev_hash: "4C8A1EE54EB10D0AAC96B1C1568D87241E6480D1DB6BD2AC38E45ACD5AD0E340",
    receipt_root: "",
    state_root: "91AA6F16EDE53AFC35C06C72F49F439BF63E7CC5D8BBEB4AB0BEB65D9A6E81DF",
    timestamp: 1568161144,
    tx_root: "69F917A8B08497EAF67860B319FF7880B21C24C0A582DBD7650CA8C1253EFDE3"
  },
  %CredoCoreNode.Blockchain.Block{
    body: nil,
    hash: "4C8A1EE54EB10D0AAC96B1C1568D87241E6480D1DB6BD2AC38E45ACD5AD0E340",
    is_valid: true,
    number: 1,
    prev_hash: "23C781D04A5E5EC18615BF486B462F11259E905CA342F41BDEDF6D797A7F24BF",
    receipt_root: "",
    state_root: "5B0ABB05AA85BD8F20259E7E3AC655E7DD2A6082F407A238CF3B7EB8BAAB7DD2",
    timestamp: 1568161075,
    tx_root: "9E3C05B62C118CB690783B6CE02AC7AB42562DEF245BDEAA7C2BC7BCADCEF9B5"
  },
  %CredoCoreNode.Blockchain.Block{
    body: nil,
    hash: "23C781D04A5E5EC18615BF486B462F11259E905CA342F41BDEDF6D797A7F24BF",
    is_valid: true,
    number: 0,
    prev_hash: "",
    receipt_root: "",
    state_root: "439BDC551DE7D25A40E205FE3F42124BB7DFC26289C8D2A1B8E1095EAA9BBED0",
    timestamp: 0,
    tx_root: "6326906CEE8511BF85B2809405C9CD84DB23B3732414EAF21D4B237A79BF836D"
  }
]
```
