### ISSUE TITLE
Participation rates calculation error

### ISSUE THREAD

**Issue by i1t** [turinginc/credo-core-node#295]
```
[error] GenServer #PID<0.775.0> terminating
** (BadMapError) expected a map, got: nil
    (elixir) lib/map.ex:437: Map.get(nil, :voting_round, nil)
    (credo_core_node) lib/credo_core_node/mining/voting_coordinator.ex:235: CredoCoreNode.Mining.VotingCoordinator.calculate_participation_rates/1
    (credo_core_node) lib/credo_core_node/mining/coinbase_transaction.ex:34: CredoCoreNode.Mining.CoinbaseTransaction.coinbase_tx_data/1
    (credo_core_node) lib/credo_core_node/mining/coinbase_transaction.ex:14: CredoCoreNode.Mining.CoinbaseTransaction.add_coinbase_tx/2
    (credo_core_node) lib/credo_core_node/blockchain/block_producer.ex:111: anonymous fn/2 in CredoCoreNode.Blockchain.BlockProducer.produce_block/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (credo_core_node) lib/credo_core_node/blockchain/block_producer.ex:102: CredoCoreNode.Blockchain.BlockProducer.produce_block/1
    (credo_core_node) lib/credo_core_node/mining/mining.ex:420: CredoCoreNode.Mining.start_mining/2
    (credo_core_node) lib/credo_core_node/workers/mine_operator.ex:37: CredoCoreNode.Workers.MineOperator.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :mine_block
State: %{interval: nil}
```

**Comment by macgregordennis** [comment]
As discussed in https://github.com/turinginc/credo-core-node/pull/298, this occurs when there are no votes for the previous block. I know we discussed storing a set of votes in the data field and we may need to revisit that to address this case.

**Comment by malroc** [comment]
@macgregordennis I actually think we don't need to store votes in the blockhain as that would seriously increase its size.
Miners store the votes locally and can use this data for validation (which is already implemented). Edge cases just need some debugging/fixing work.
